services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: tickets_app
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 9906:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
  
volumes:
  db_data: