<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Immagini\alga.png" />
    <None Remove="Immagini\background.png" />
    <None Remove="Immagini\banco.png" />
    <None Remove="Immagini\cavalluccio.png" />
    <None Remove="Immagini\corallo.png" />
    <None Remove="Immagini\medusa.png" />
    <None Remove="Immagini\pesce.png" />
    <None Remove="Immagini\pesce1.png" />
    <None Remove="Immagini\pesce2.png" />
    <None Remove="Immagini\pesce3.png" />
    <None Remove="Immagini\pesce4.png" />
    <None Remove="Immagini\pesce5.png" />
    <None Remove="Immagini\pescepagliaccio.png" />
    <None Remove="Immagini\pescepalla.png" />
    <None Remove="Immagini\sfondo.png" />
    <None Remove="Immagini\tartaruga.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Immagini\alga.png" />
    <Resource Include="Immagini\banco.png" />
    <Resource Include="Immagini\cavalluccio.png" />
    <Resource Include="Immagini\corallo.png" />
    <Resource Include="Immagini\medusa.png" />
    <Resource Include="Immagini\pescepalla.png" />
    <Resource Include="Immagini\sfondo.png" />
    <Resource Include="Immagini\tartaruga.png" />
  </ItemGroup>

  <Import Project="..\ProgettoCondiviso\ProgettoCondiviso.projitems" Label="Shared" />

</Project>
