<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Immagini\background.png" />
    <None Remove="Immagini\pescepalla.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Immagini\background.png" />
    <Resource Include="Immagini\pescepalla.png" />
  </ItemGroup>

</Project>
